""" Interface1.py --

 UI generated by GUI Builder Build 146 on 2015-07-13 10:03:18 from:
    D:/Google Drive/My Documents/Github/Python/PasswordStorage/Interface1.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from Interface1_ui import Interface1

# BEGIN USER CODE global

# END USER CODE global

class CustomInterface1(Interface1):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # _button_2_command --
    #
    # Callback to handle _button_2 widget option -command
    def _button_2_command(self, *args):
        pass

    # _entry_1_invalidcommand --
    #
    # Callback to handle _entry_1 widget option -invalidcommand
    def _entry_1_invalidcommand(self, *args):
        pass

    # _entry_1_validatecommand --
    #
    # Callback to handle _entry_1 widget option -validatecommand
    def _entry_1_validatecommand(self, *args):
        pass

    # _entry_1_xscrollcommand --
    #
    # Callback to handle _entry_1 widget option -xscrollcommand
    def _entry_1_xscrollcommand(self, *args):
        pass

    # _entry_2_invalidcommand --
    #
    # Callback to handle _entry_2 widget option -invalidcommand
    def _entry_2_invalidcommand(self, *args):
        pass

    # _entry_2_validatecommand --
    #
    # Callback to handle _entry_2 widget option -validatecommand
    def _entry_2_validatecommand(self, *args):
        pass

    # _entry_2_xscrollcommand --
    #
    # Callback to handle _entry_2 widget option -xscrollcommand
    def _entry_2_xscrollcommand(self, *args):
        pass

    # _listbox_1_xscrollcommand --
    #
    # Callback to handle _listbox_1 widget option -xscrollcommand
    def _listbox_1_xscrollcommand(self, *args):
        pass

    # _listbox_1_yscrollcommand --
    #
    # Callback to handle _listbox_1 widget option -yscrollcommand
    def _listbox_1_yscrollcommand(self, *args):
        pass

    # _radiobutton_3_command --
    #
    # Callback to handle _radiobutton_3 widget option -command
    def _radiobutton_3_command(self, *args):
        pass

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomInterface1(root)
    root.title('Interface1')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
