""" Interface1_ui.py --

 UI generated by GUI Builder Build 146 on 2015-07-13 10:03:18 from:
    D:/Google Drive/My Documents/Github/Python/PasswordStorage/Interface1.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Interface1(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._frame_5 = Tkinter.Frame(root,
        )
        self._frame_6 = Tkinter.Frame(root,
        )
        self._frame_7 = Tkinter.Frame(root,
        )
        self._button_2 = Tkinter.Button(root,
            text = "_button_2",
        )
        self._label_1 = Tkinter.Label(root,
            text = "_label_1",
        )
        self._radiobutton_3 = Tkinter.Radiobutton(self._frame_6,
            text = "_radiobutton_3",
        )
        self._entry_1 = Tkinter.Entry(self._frame_6,
            insertwidth = 10,
            width = 0,
        )
        self._label_2 = Tkinter.Label(root,
            text = "_label_2",
        )
        self._listbox_1 = Tkinter.Listbox(root,
            height = 0,
            width = 0,
        )
        self._label_3 = Tkinter.Label(root,
            text = "_label_3",
        )
        self._label_4 = Tkinter.Label(self._frame_7,
            text = "_label_4",
        )
        self._entry_2 = Tkinter.Entry(self._frame_7,
            width = 0,
        )
        self._label_5 = Tkinter.Label(root,
            text = "_label_5",
        )

        # widget commands

        self._button_2.configure(
            command = self._button_2_command
        )
        self._radiobutton_3.configure(
            command = self._radiobutton_3_command
        )
        self._entry_1.configure(
            invalidcommand = self._entry_1_invalidcommand
        )
        self._entry_1.configure(
            validatecommand = self._entry_1_validatecommand
        )
        self._entry_1.configure(
            xscrollcommand = self._entry_1_xscrollcommand
        )
        self._listbox_1.configure(
            xscrollcommand = self._listbox_1_xscrollcommand
        )
        self._listbox_1.configure(
            yscrollcommand = self._listbox_1_yscrollcommand
        )
        self._entry_2.configure(
            invalidcommand = self._entry_2_invalidcommand
        )
        self._entry_2.configure(
            validatecommand = self._entry_2_validatecommand
        )
        self._entry_2.configure(
            xscrollcommand = self._entry_2_xscrollcommand
        )


        # Geometry Management
        self._frame_5.grid(
            in_    = root,
            column = 1,
            row    = 10,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_6.grid(
            in_    = root,
            column = 1,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._frame_7.grid(
            in_    = root,
            column = 1,
            row    = 7,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._button_2.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._label_1.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._radiobutton_3.grid(
            in_    = self._frame_6,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._entry_1.grid(
            in_    = self._frame_6,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._label_2.grid(
            in_    = root,
            column = 1,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._listbox_1.grid(
            in_    = root,
            column = 1,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._label_3.grid(
            in_    = root,
            column = 1,
            row    = 6,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._label_4.grid(
            in_    = self._frame_7,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._entry_2.grid(
            in_    = self._frame_7,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )
        self._label_5.grid(
            in_    = root,
            column = 1,
            row    = 8,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(4, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(5, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(6, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(7, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(8, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(9, weight = 0, minsize = 73, pad = 0)
        root.grid_rowconfigure(10, weight = 0, minsize = 180, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 238, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 263, pad = 0)
        self._frame_6.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_6.grid_columnconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_6.grid_columnconfigure(2, weight = 0, minsize = 303, pad = 0)
        self._frame_7.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_7.grid_columnconfigure(1, weight = 0, minsize = 40, pad = 0)
        self._frame_7.grid_columnconfigure(2, weight = 0, minsize = 40, pad = 0)


