""" PasswordApp1x1_ui.py --

 UI generated by GUI Builder Build 146 on 2015-07-14 12:10:27 from:
    D:/Google Drive/My Documents/Github/Python/PasswordStorage/PasswordApp1x1.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class PasswordApp1x1(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._frame_6 = Tkinter.Frame(root,
        )
        self.btnNewVault = Tkinter.Button(root,
            text = "Create New Vault",
        )
        self.lblSelectAVault = Tkinter.Label(root,
            text = "Select A Vault",
        )
        self.radUsingText = Tkinter.Radiobutton(self._frame_6,
            text = "Using Text",
        )
        self.entVaultText = Tkinter.Entry(self._frame_6,
            insertwidth = 10,
            width = 40,
        )
        self.lblSelectAVaultKey = Tkinter.Label(root,
            text = "Select A Vault Key",
        )
        self.lblPasswordSelection = Tkinter.Label(root,
            text = "Enter The Identifier For The Desired Password Below",
        )
        self.entPasswordSearch = Tkinter.Entry(root,
            width = 0,
        )
        self.lstPasswords = Tkinter.Listbox(root,
            height = 0,
            width = 0,
        )
        self.btnModifyVault = Tkinter.Button(root,
            text = "Modify Vault",
        )
        self.btnEnterKeyCredentials = Tkinter.Button(root,
            text = "Enter Key Credentials",
        )
        self.lstVaultKeySelector = Tkinter.Listbox(root,
            height = 0,
            width = 0,
        )

        # widget commands

        self.btnNewVault.configure(
            command = self.btnNewVault_command
        )
        self.radUsingText.configure(
            command = self.radUsingText_command
        )
        self.entVaultText.configure(
            invalidcommand = self.entVaultText_invalidcommand
        )
        self.entVaultText.configure(
            validatecommand = self.entVaultText_validatecommand
        )
        self.entVaultText.configure(
            xscrollcommand = self.entVaultText_xscrollcommand
        )
        self.entPasswordSearch.configure(
            invalidcommand = self.entPasswordSearch_invalidcommand
        )
        self.entPasswordSearch.configure(
            validatecommand = self.entPasswordSearch_validatecommand
        )
        self.entPasswordSearch.configure(
            xscrollcommand = self.entPasswordSearch_xscrollcommand
        )
        self.lstPasswords.configure(
            xscrollcommand = self.lstPasswords_xscrollcommand
        )
        self.lstPasswords.configure(
            yscrollcommand = self.lstPasswords_yscrollcommand
        )
        self.btnModifyVault.configure(
            command = self.btnModifyVault_command
        )
        self.btnEnterKeyCredentials.configure(
            command = self.btnEnterKeyCredentials_command
        )
        self.lstVaultKeySelector.configure(
            xscrollcommand = self.lstVaultKeySelector_xscrollcommand
        )
        self.lstVaultKeySelector.configure(
            yscrollcommand = self.lstVaultKeySelector_yscrollcommand
        )


        # Geometry Management
        self._frame_6.grid(
            in_    = root,
            column = 1,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self.btnNewVault.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self.lblSelectAVault.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self.radUsingText.grid(
            in_    = self._frame_6,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self.entVaultText.grid(
            in_    = self._frame_6,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "w"
        )
        self.lblSelectAVaultKey.grid(
            in_    = root,
            column = 1,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self.lblPasswordSelection.grid(
            in_    = root,
            column = 1,
            row    = 7,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self.entPasswordSearch.grid(
            in_    = root,
            column = 1,
            row    = 8,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )
        self.lstPasswords.grid(
            in_    = root,
            column = 1,
            row    = 9,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self.btnModifyVault.grid(
            in_    = root,
            column = 1,
            row    = 10,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self.btnEnterKeyCredentials.grid(
            in_    = root,
            column = 1,
            row    = 6,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self.lstVaultKeySelector.grid(
            in_    = root,
            column = 1,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(4, weight = 0, minsize = 5, pad = 0)
        root.grid_rowconfigure(5, weight = 0, minsize = 96, pad = 0)
        root.grid_rowconfigure(6, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(7, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(8, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(9, weight = 0, minsize = 64, pad = 0)
        root.grid_rowconfigure(10, weight = 0, minsize = 2, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 138, pad = 0)
        self._frame_6.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_6.grid_columnconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_6.grid_columnconfigure(2, weight = 0, minsize = 226, pad = 0)


