""" PasswordApp1_ui.py --

 UI generated by GUI Builder Build 146 on 2015-07-14 11:41:33 from:
    D:/Google Drive/My Documents/Github/Python/PasswordStorage/PasswordApp1.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class PasswordApp1(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._frame_6 = Tkinter.Frame(root,
        )
        self.btnNewVault = Tkinter.Button(root,
            text = "Create New Vault",
        )
        self.lblSelectAVault = Tkinter.Label(root,
            text = "Select A Vault",
        )
        self.radUsingText = Tkinter.Radiobutton(self._frame_6,
            text = "Using Text",
        )
        self.entVaultText = Tkinter.Entry(self._frame_6,
            insertwidth = 10,
            width = 40,
        )
        self.lblSelectAVaultKey = Tkinter.Label(root,
            text = "Select A Vault Key",
        )
        self._listbox_1 = Tkinter.Listbox(root,
            height = 0,
            width = 0,
        )
        self.lblPasswordSelection = Tkinter.Label(root,
            text = "Enter the identifier for the desired password below",
        )
        self.entPasswordSearch = Tkinter.Entry(root,
            width = 0,
        )
        self._listbox_2 = Tkinter.Listbox(root,
            height = 0,
            width = 0,
        )
        self._label_6 = Tkinter.Label(root,
            text = "_label_6",
        )
        self._label_7 = Tkinter.Label(root,
            text = "_label_7",
        )
        self._button_3 = Tkinter.Button(root,
            text = "_button_3",
        )
        self.btnEnterKeyCredentials = Tkinter.Button(root,
            text = "Enter Key Credentials",
        )

        # widget commands

        self.btnNewVault.configure(
            command = self.btnNewVault_command
        )
        self.radUsingText.configure(
            command = self.radUsingText_command
        )
        self.entVaultText.configure(
            invalidcommand = self.entVaultText_invalidcommand
        )
        self.entVaultText.configure(
            validatecommand = self.entVaultText_validatecommand
        )
        self.entVaultText.configure(
            xscrollcommand = self.entVaultText_xscrollcommand
        )
        self._listbox_1.configure(
            xscrollcommand = self._listbox_1_xscrollcommand
        )
        self._listbox_1.configure(
            yscrollcommand = self._listbox_1_yscrollcommand
        )
        self.entPasswordSearch.configure(
            invalidcommand = self.entPasswordSearch_invalidcommand
        )
        self.entPasswordSearch.configure(
            validatecommand = self.entPasswordSearch_validatecommand
        )
        self.entPasswordSearch.configure(
            xscrollcommand = self.entPasswordSearch_xscrollcommand
        )
        self._listbox_2.configure(
            xscrollcommand = self._listbox_2_xscrollcommand
        )
        self._listbox_2.configure(
            yscrollcommand = self._listbox_2_yscrollcommand
        )
        self._button_3.configure(
            command = self._button_3_command
        )
        self.btnEnterKeyCredentials.configure(
            command = self.btnEnterKeyCredentials_command
        )


        # Geometry Management
        self._frame_6.grid(
            in_    = root,
            column = 1,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self.btnNewVault.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self.lblSelectAVault.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self.radUsingText.grid(
            in_    = self._frame_6,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self.entVaultText.grid(
            in_    = self._frame_6,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "w"
        )
        self.lblSelectAVaultKey.grid(
            in_    = root,
            column = 1,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self._listbox_1.grid(
            in_    = root,
            column = 1,
            row    = 5,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self.lblPasswordSelection.grid(
            in_    = root,
            column = 1,
            row    = 7,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )
        self.entPasswordSearch.grid(
            in_    = root,
            column = 1,
            row    = 8,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "ew"
        )
        self._listbox_2.grid(
            in_    = root,
            column = 1,
            row    = 9,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._label_6.grid(
            in_    = root,
            column = 1,
            row    = 10,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_7.grid(
            in_    = root,
            column = 1,
            row    = 11,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_3.grid(
            in_    = root,
            column = 1,
            row    = 12,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.btnEnterKeyCredentials.grid(
            in_    = root,
            column = 1,
            row    = 6,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nw"
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(4, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(5, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(6, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(7, weight = 0, minsize = 2, pad = 0)
        root.grid_rowconfigure(8, weight = 0, minsize = 21, pad = 0)
        root.grid_rowconfigure(9, weight = 0, minsize = 73, pad = 0)
        root.grid_rowconfigure(10, weight = 0, minsize = 59, pad = 0)
        root.grid_rowconfigure(11, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(12, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 183, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 2, pad = 0)
        self._frame_6.grid_rowconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_6.grid_columnconfigure(1, weight = 0, minsize = 2, pad = 0)
        self._frame_6.grid_columnconfigure(2, weight = 0, minsize = 257, pad = 0)


