""" PasswordApp1.py --

 UI generated by GUI Builder Build 146 on 2015-07-14 11:41:33 from:
    D:/Google Drive/My Documents/Github/Python/PasswordStorage/PasswordApp1.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from PasswordApp1_ui import PasswordApp1

# BEGIN USER CODE global

# END USER CODE global

class CustomPasswordApp1(PasswordApp1):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # _button_3_command --
    #
    # Callback to handle _button_3 widget option -command
    def _button_3_command(self, *args):
        pass

    # _listbox_1_xscrollcommand --
    #
    # Callback to handle _listbox_1 widget option -xscrollcommand
    def _listbox_1_xscrollcommand(self, *args):
        pass

    # _listbox_1_yscrollcommand --
    #
    # Callback to handle _listbox_1 widget option -yscrollcommand
    def _listbox_1_yscrollcommand(self, *args):
        pass

    # _listbox_2_xscrollcommand --
    #
    # Callback to handle _listbox_2 widget option -xscrollcommand
    def _listbox_2_xscrollcommand(self, *args):
        pass

    # _listbox_2_yscrollcommand --
    #
    # Callback to handle _listbox_2 widget option -yscrollcommand
    def _listbox_2_yscrollcommand(self, *args):
        pass

    # btnEnterKeyCredentials_command --
    #
    # Callback to handle btnEnterKeyCredentials widget option -command
    def btnEnterKeyCredentials_command(self, *args):
        pass

    # btnNewVault_command --
    #
    # Callback to handle btnNewVault widget option -command
    def btnNewVault_command(self, *args):
        pass

    # entPasswordSearch_invalidcommand --
    #
    # Callback to handle entPasswordSearch widget option -invalidcommand
    def entPasswordSearch_invalidcommand(self, *args):
        pass

    # entPasswordSearch_validatecommand --
    #
    # Callback to handle entPasswordSearch widget option -validatecommand
    def entPasswordSearch_validatecommand(self, *args):
        pass

    # entPasswordSearch_xscrollcommand --
    #
    # Callback to handle entPasswordSearch widget option -xscrollcommand
    def entPasswordSearch_xscrollcommand(self, *args):
        pass

    # entVaultText_invalidcommand --
    #
    # Callback to handle entVaultText widget option -invalidcommand
    def entVaultText_invalidcommand(self, *args):
        pass

    # entVaultText_validatecommand --
    #
    # Callback to handle entVaultText widget option -validatecommand
    def entVaultText_validatecommand(self, *args):
        pass

    # entVaultText_xscrollcommand --
    #
    # Callback to handle entVaultText widget option -xscrollcommand
    def entVaultText_xscrollcommand(self, *args):
        pass

    # radUsingText_command --
    #
    # Callback to handle radUsingText widget option -command
    def radUsingText_command(self, *args):
        pass

    # _button_2_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _button_2_command(self, *args):
        pass

    # _entry_1_invalidcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _entry_1_invalidcommand(self, *args):
        pass

    # _entry_1_validatecommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _entry_1_validatecommand(self, *args):
        pass

    # _entry_1_xscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _entry_1_xscrollcommand(self, *args):
        pass

    # _entry_2_invalidcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _entry_2_invalidcommand(self, *args):
        pass

    # _entry_2_validatecommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _entry_2_validatecommand(self, *args):
        pass

    # _entry_2_xscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _entry_2_xscrollcommand(self, *args):
        pass

    # _entry_3_invalidcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _entry_3_invalidcommand(self, *args):
        pass

    # _entry_3_validatecommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _entry_3_validatecommand(self, *args):
        pass

    # _entry_3_xscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _entry_3_xscrollcommand(self, *args):
        pass

    # _radiobutton_3_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _radiobutton_3_command(self, *args):
        pass

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomPasswordApp1(root)
    root.title('PasswordApp1')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
