""" Beginning Screen_ui.py --

 UI generated by GUI Builder Build 146 on 2015-07-21 14:37:53 from:
    D:/Google Drive/My Documents/Github/Python/PasswordStorage/Komodo GUIBuilder/Beginning Screen.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Beginning_Screen(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._label_1 = Tkinter.Label(root,
            font = "{MS Sans Serif} 12 bold",
            text = "Select an Option",
        )
        self._button_1 = Tkinter.Button(root,
            text = "Create Vault",
        )
        self._button_2 = Tkinter.Button(root,
            text = "Open Vault",
        )

        # widget commands

        self._button_1.configure(
            command = self._button_1_command
        )
        self._button_2.configure(
            command = self._button_2_command
        )


        # Geometry Management
        self._label_1.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_1.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._button_2.grid(
            in_    = root,
            column = 1,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 30, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 39, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 184, pad = 0)


